DEFAULT_DESCRIPTION = 'Click the 👍 below if you would like to join this queue.'
SOLO_ICON_URL = 'https://i.imgur.com/TN7s2t3.png'
SQUAD_ICON_URL = 'https://i.imgur.com/HKBers5.png'
PLAY_ICON_URL = 'https://i.imgur.com/ZnEOwyj.png'
THUMBS_UP = '👍'
CHECKMARK = '✅'
CANCEL = '❌'
UNCONFIRMED = '❓'